//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.Infraestructura.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aula()
        {
            this.AulaAlumno = new HashSet<AulaAlumno>();
            this.Tarea = new HashSet<Tarea>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public bool Eliminado { get; set; }
        public int DocenteId { get; set; }
        public int CicloId { get; set; }
        public int MateriaId { get; set; }
        public string Codigo { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Ciclo Ciclo { get; set; }
        public virtual Materia Materia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AulaAlumno> AulaAlumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarea> Tarea { get; set; }
    }
}
